"""The published API surface must keep describing the surface the mod uses.

A signature list that drifts is worse than none, because it looks authoritative.
Two directions matter and they are independent:

  * The report must cover every hook the mod declares. A hook the report does not
    describe is a hook a reader cannot check, and the ones it misses are exactly
    the ones that cost a day to find -- a popup that blocks on a key, a map that
    enumerates through a struct, a strip that turns out to be a render.

  * The report must be pinned to the build it was taken from. It carries the
    assembly's sha256 and version, so a game update that moves a signature is
    detectable rather than something a reader discovers by trying.

Neither is verifiable without the game, so both are opt-in and run in the
install-handoff job alongside the metadata probe.
"""
import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "builds/api-surface.json"

# Every Harmony patch the mod installs, as Type -> the method it patches. Kept
# beside the report rather than derived from it, because deriving it would make
# this test agree with whatever the report happens to say.
HOOKS = {
    "XRL.UI.Popup": [
        "Show", "ShowBlock", "ShowBlockPrompt", "ShowBlockSpace",
        "ShowBlockWithCopy", "ShowSpace", "PickOption",
    ],
    "XRL.UI.ConversationUI": ["HaveConversation", "Select", "Input", "Render"],
    "ConsoleLib.Console.Keyboard": ["PushMouseEvent", "IdleWait"],
    "XRL.Core.XRLCore": ["WriteConsoleLine", "RegisterNewMessageLogEntryCallback"],
    "XRL.World.Quest": [
        "ShowStartPopup", "ShowFailPopup", "ShowFailStepPopup",
        "ShowFinishPopup", "ShowFinishStepPopup",
    ],
    "Qud.UI.WorldGenerationScreen": ["ShowWorldGenerationScreen"],
    "XRL.World.GameObject": ["FireEvent", "GetPart"],
    "XRL.World.Parts.Inventory": ["GetEquipmentListForSlot"],
    "XRL.XRLGame": ["Quests", "FinishedQuests"],
    "ConsoleLib.Console.Markup": ["Strip"],
}

# Read from the mod's own sources, so the list above is a claim the test checks
# rather than a list that has to be maintained by hand.
PATCH_SOURCES = [
    ROOT / "mod/QudGym/PromptProbe.cs",
    ROOT / "mod/QudGym/TurnProbe.cs",
    ROOT / "mod/QudGym/WorldGenGate.cs",
    ROOT / "mod/QudGym/PushProbe.cs",
    ROOT / "mod/QudGym.Impl/Session.fs",
]

# What the mod reads through reflection, and so depends on without patching.
REFLECTED = {
    "XRL.UI.QuestLog": ["GetLinesForQuest"],
    "XRL.Collections.StringMap`1": ["Count", "Item", "ContainsKey"],
    "XRL.World.Anatomy.BodyPart": ["Type", "GetOrdinalName", "Primary"],
    "XRL.World.Parts.Body": ["GetParts"],
    "XRL.Messages": ["Message"],
    "Qud.UI.SingletonWindowBase": [],
    "XRL.UI.Screens": ["Show"],
    "XRL.World.Parts.ConversationScript": ["AttemptConversation"],
    "XRL.World.Event": ["SetParameter"],
}

# Simple names of the types above, for the source scan.
REFLECTED_SIMPLE = {t.split(".")[-1].split("`")[0] for t in REFLECTED}

# Names the mod writes that are not a hook target: reflection helpers, and the
# short forms HarmonyPatch attributes use.
ALIASES = {"IEvent", "Event", "The", "Game", "Core", "Popup", "Keyboard"}


def _load():
    if not REPORT.is_file():
        pytest.skip("api-surface.json is generated by the install-handoff job")
    return json.loads(REPORT.read_text(encoding="utf-8"))


def test_report_declares_it_reads_metadata_and_runs_no_game_code():
    """The report's own honesty is the product; assert it rather than trust it."""
    report = _load()
    assert report["schema_version"] == "qud-api-metadata/1"
    assert report["runtime_hooks_verified"] is False
    assert report["game_code_executed"] is False
    assert report["assembly"]["sha256"] and len(report["assembly"]["sha256"]) == 64


def test_report_carries_no_local_path():
    """A report meant to be shared must not leak where the game is installed."""
    raw = REPORT.read_text(encoding="utf-8")
    for leak in ("/Users/", "/home/", "CoQ.app", "Library/Application Support"):
        assert leak not in raw, f"{leak!r} appears in the published surface"


@pytest.mark.parametrize("type_name", sorted(HOOKS))
def test_every_patched_type_and_method_is_described(type_name):
    report = _load()
    found = {q["type_name"]: q for q in report["queries"]}
    assert type_name in found, f"{type_name} is patched but absent from the surface report"
    query = found[type_name]
    assert query["found"] is True
    members = {m["name"] for m in query["members"]}
    missing = [m for m in HOOKS[type_name] if m not in members]
    assert not missing, f"{type_name}: not described: {missing}"


@pytest.mark.parametrize("type_name", sorted(REFLECTED))
def test_every_reflected_type_is_described(type_name):
    """Reflection is a dependency the report cannot show, so it is named here."""
    report = _load()
    found = {q["type_name"]: q for q in report["queries"]}
    assert type_name in found, f"{type_name} is read by reflection but not described"


def test_the_patch_list_matches_the_sources():
    """A hook added to the mod without adding it here fails, and vice versa.

    Derived from the sources on purpose: the alternative is a hand-kept list that
    is correct until the next hook, and the failure it hides is a reader who
    trusts a report that has stopped describing the code.

    Matched on the simple name, because that is what a HarmonyPatch attribute
    writes -- `typeof(XRL.UI.Popup)` and the report's `XRL.UI.Popup` are the same
    type by a suffix, and demanding an exact full name would only mean the test
    and the report have to agree on a spelling nobody types.
    """
    report = _load()
    described_simple = {q["type_name"].split(".")[-1].split("+")[-1] for q in report["queries"]}

    patched = set()
    for path in PATCH_SOURCES:
        text = path.read_text(encoding="utf-8")
        # typeof(NS.Type) inside a HarmonyPatch attribute, and nameof(Type.Member)
        # beside it, which is where the patched member is named.
        for match in re.finditer(r"typeof\(([A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)+)\)", text):
            patched.add(match.group(1).split(".")[-1])
        for match in re.finditer(r"nameof\(([A-Za-z0-9_.]+)\.([A-Za-z0-9_]+)\)", text):
            patched.add(match.group(1).split(".")[-1])

    assert patched, "no patches found in the sources; the scan is wrong"
    # Reflection targets are described in REFLECTED rather than patched, and a few
    # names appear in the mod as data rather than as a hook target.
    undeclared = sorted(
        t for t in patched
        if t not in described_simple and t not in REFLECTED_SIMPLE and t not in ALIASES
    )
    assert not undeclared, f"patched or read but not in the surface report: {undeclared}"


def test_report_is_pinned_to_one_build():
    """One report, one build. A mixed report is a report nobody can trust."""
    report = _load()
    assert report["assembly"]["sha256"] == report["assembly"]["sha256"].lower()
    versions = {q.get("assembly_version") for q in report["queries"] if q.get("assembly_version")}
    assert len(versions) <= 1, f"report mixes assembly versions: {versions}"
