from typing import Protocol
from .models import Capabilities, Observation, SnapshotHandle, StateHash, Transition


class Backend(Protocol):
    """One serialized controller per environment; snapshots are optional privileges."""
    def capabilities(self) -> Capabilities: ...
    def reset(self, *, seed: int = 0) -> Transition: ...
    def observe(self) -> Observation: ...
    def step(self, action_id: str, *, decision_id: str) -> Transition: ...
    def snapshot(self) -> SnapshotHandle: ...
    def restore(self, handle: str) -> Transition: ...
    def release(self, handle: str) -> None: ...
    def state_hash(self) -> StateHash: ...
    def close(self) -> None: ...
